// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrb7FkYG_l6t4Hux01yk0E9BwOd1u3I9U',
    appId: '1:561523297767:web:f3875c367a36f1beef0142',
    messagingSenderId: '561523297767',
    projectId: 'fluttertask-44ece',
    authDomain: 'fluttertask-44ece.firebaseapp.com',
    storageBucket: 'fluttertask-44ece.appspot.com',
    measurementId: 'G-1KMGLPDHJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVGrZ7k88xxj97TcpwwzHHqWJwLwLutaM',
    appId: '1:561523297767:android:7c123a8287238906ef0142',
    messagingSenderId: '561523297767',
    projectId: 'fluttertask-44ece',
    storageBucket: 'fluttertask-44ece.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6qE11sJQhKxVxooYSBUUh9s8hGtRBjxU',
    appId: '1:561523297767:ios:c7b62ab7974f3c3aef0142',
    messagingSenderId: '561523297767',
    projectId: 'fluttertask-44ece',
    storageBucket: 'fluttertask-44ece.appspot.com',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6qE11sJQhKxVxooYSBUUh9s8hGtRBjxU',
    appId: '1:561523297767:ios:dcfec0b119adb6ebef0142',
    messagingSenderId: '561523297767',
    projectId: 'fluttertask-44ece',
    storageBucket: 'fluttertask-44ece.appspot.com',
    iosBundleId: 'com.example.flutterTask.RunnerTests',
  );
}
